spring:
  application: 
    name: hystrix-request


server:
  context-path: /
  port: 6002
  
eureka:
  client:
    service-url:
      ##单点配置:
      defaultZone: http://eureka1:8001/eureka/
#断路器超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000

custom:
  rest:
    connect-timeout: 10000
    connection-rest-imeout: 10000
    read-timeout: 30000


