spring:
  application: 
    name: hystrix-request


server:
  context-path: /
  port: 6003

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000


custom:
  rest:
    Connect-timeout: 1000
    Connection-request-timeout: 1000
    read-timeout: 5000
