spring:
  application: 
    name: feign-consumer

server:
  context-path: /
  port: 7002
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000

feign:
  hystrix:
    enabled: true
  compression:
    request:
      mime-types:
        - text/xml, applicaton/xml, applicaton/json
      min-request-size: 2048
    response:
      enabled: true
