spring:
  application: 
    name: client-service

server:
  context-path: /
  port: 7001
  
eureka:
  client:
    service-url:
      ##单点配置:
#      defaultZone: http://eureka1:8001/eureka/
      ##高可用配置
      defaultZone: http://eureka1:8001/eureka/
  